import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
import Sketch from "@/components/sketch";
import { useState } from "react";

let data = {
  nft: [190, 295, 100],
};
let arr = [100, 190, 50];

export default function Home() {
  const [randomArr, setRandomArr] = useState([
    arr[0] * Math.random(),
    arr[1] * Math.random(),
    arr[2] * Math.random(),
  ]);

  const generatorFunction = () => {
    setRandomArr([
      arr[0] * Math.random(),
      arr[1] * Math.random(),
      arr[2] * Math.random(),
    ]);
  };

  return (
    <>
      <Head>
        <title>Spiro: NFT Tradecenter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../resources/compassicon.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <div className={styles.mainContent}>
          <div className={styles.generatorLeft}>
            <div className={styles.divider}>
              <div className={styles.dividerTitle}>Instructions on use</div>
              <div className={styles.dividerContent}>Click on the generate button to generate a pattern that can further be
              converted in to an NFT.User can check the rarity and estimated value on the community store</div>
            </div>
            <div className={styles.divider}>
              <div className={styles.dividerTitle}></div>
              <div className={styles.dividerContent}>The webiste will automatically generate a spiro pattern for you,the same can be discarded if the user needs a new pattern or owns the same</div>
            </div>
            <div className={styles.divider}>
              <div className={styles.dividerTitle}>Rarity levels</div>
              <div className={styles.dividerContent}>There are 3 defined rarity levels:
                <br></br>
                Common:Nfts of this rarity are very easily available and can be bought for as low as 0.01$
              <br />
              Rare:Rare NFts are not easy to acquire and hold significant cost price.
              <br />
              Legendary:These NFTs are very hard to find and can go as high as $1 million
            </div>
            </div>
            <div className={styles.divider}>
              <button
                onClick={generatorFunction}
                className={styles.generateButton}
              >
                Generate
              </button>
            </div>
          </div>
          <div className={styles.generatorRight}>
            <div className={styles.generator}>
              <Sketch
                data={{
                  nft: [
                    arr[0] * Math.random(),
                    arr[1] * Math.random(),
                    arr[2] * Math.random(),
                  ],
                }}
              />
            </div>
            <div className={styles.generatorOptions}>
              <button className={styles.discardButton}>Discard</button>
              <button className={styles.storeButton}>Store</button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
