import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./nfticon.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <div className={styles.mainContent}>
          <div className={styles.generatorLeft}>
            <div className={styles.divider}>
              <div className={styles.dividerTitle}>Title</div>
              <div className={styles.dividerContent}>
                <ul className={styles.stepsList}>
                  <li className={styles.listItem}>step1:add rule here</li>
                  <li className={styles.listItem}>step2:add rule here</li>
                  <li className={styles.listItem}>step3:add rule here</li>
                  <li className={styles.listItem}>step4:add rule here</li>
                </ul>
              </div>
            </div>
          </div>
          <div className={styles.generatorRight}>
            <div className={styles.generator}></div>
            <div className={styles.generatorOptions}>
              <button className={styles.discardButton}>Discard</button>
              <div className={styles.rhsGeneratorOptions}>
                <button className={styles.storeButton}>store</button>
                <button className={styles.collectButton}>store</button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
