import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./nfticon.png" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <div className={styles.mainContent}>
          <div className={styles.generatorLeft}></div>
          <div className={styles.generatorRight}>
            <div className={styles.generator}>
              <div className="sketch" style={{ width: "100%", height: "100%" }}>
                <iframe
                  className="p5frame"
                  style={{ width: "100%", height: "100%" }}
                  srcDoc={`
            <!DOCTYPE html>
            <html lang="en">
                <head>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/addons/p5.sound.min.js"></script>
                <style>
                    html, body {
                        margin: 0;
                        padding: 0;
                        height: 100vh;
                        width: 100vw;
                        display:flex;
                        flex-direction: column;
                        justify-content: center;
                        align-items: center;
                    }
                    canvas {
                        display: block;
                    }
                </style>                      
                <meta charset="utf-8" />
            
                </head>
                <body>
                <script src=${"/sketch.js"}></script>
                </body>
            </html> `}
                ></iframe>
              </div>
            </div>
            <div className={styles.generatorOptions}>
              <button className={styles.discardButton}>Discard</button>
              <button className={styles.storeButton}>store</button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
